name: book_repair
description: book_repair
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.4.2
  intl: ^0.17.0

flutter_native_splash:
  color: "#8711d6"
  image: assets/splash_background.png
  background_image: assets/splash_background.png

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
